autoactivate: true
lang:
  prefix: "&bAutoPlant &8>> &f"
  reload_done: "&aReload done!"
  activated: "&aAutoPlant activated!"
  deactivated: "&cAutoPlant deactivated!"
  not_ready: "&bThis plant is not ready yet..."
  world_added_to_blacklist: "Auto-Replant toggled &coff &fin this World!"
  world_removed_from_blacklist: "Auto-Replant toggled &aon &fin this World!"
config:
  user_perm: 'zf.autoreplant.user'
  admin_perm: 'zf.autoreplant.admin'
  material_list:
  - BEETROOTS
  - CARROTS
  - NETHER_WART
  - POTATOES
  - WHEAT
  world_blacklist:
  - ExampleWorld
  player_list:
    2b1db394-43bb-4685-a4c9-8370a81aa159: true
    34869720-c776-4b18-ad05-e507e45cc3fc: false
