name: AutoReplant
version: 0.3.0
author: Blautee
api-version: 1.19

softdepend: [WorldGuard, WorldEdit]

main: de.blautee.autoreplant.Main
description: Automates the Replant Process so you don't have to care about that on your Server!

commands:
  autoreplant:
    description: Toggle the function or reload config with admin permission
    aliases: arp
